### ISSUE TITLE
import mapping from collections.abc

### ISSUE THREAD

**Issue by ldartez** [wieldphysics/wield-iirrational#3]
Since 3.10, `Mapping` must be imported via `collections.abc` rather than from `collections` directly. 

Running with 3.10 produces the error below (provided by SURF student Caden Swain):
```
File ~\anaconda3\lib\site-packages\wield\iirrational\v2\arguments\standardargs.py:54 in normalize_roots
    elif isinstance(val, collections.Mapping):

AttributeError: module 'collections' has no attribute 'Mapping'
```

**Comment by IanAMacMillan** [comment]
There is another instance that should also be changed that is from my old pull request https://github.com/wieldphysics/wield-iirrational/pull/2/commits/24b94653ea1ae198fbf1c3fb72ad667ba129b219
